# Generated by Django 3.2.8 on 2021-10-12 21:51

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('user_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_address', models.EmailField(max_length=254)),
                ('about_user', models.TextField()),
                ('country_name', models.CharField(max_length=60)),
                ('city_name', models.CharField(max_length=60)),
                ('address_1', models.CharField(max_length=60)),
                ('address_2', models.CharField(max_length=60)),
                ('avator', models.ImageField(upload_to=authentication.models.upload_location)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Users Profiles',
            },
        ),
    ]
